spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/purbashaqms?serverTimezone=Asia/Kolkata
    username: root
    password: local123
  hikari:
    connection-timeout: 20000
    minimum-idle: 5
    maximum-pool-size: 12
    idle-timeout: 300000
    max-lifetime: 1200000
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    properties:
      hibernate:
        format_sql: false

application:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        secret: vRl+lRZtaKL3IASrF6wR3Xe0ToyniX9Jam1tAZ05qjWl4gZGyLyPPNTG/vy45DI3uX+LiQXXFaxgAWjy4gg8Bg==
        # Token validity in secs -- is valid 24 hours
        token-validity-in-seconds: 86400
        # Token validity in secs for remember me
        token-validity-in-seconds-for-remember-me: 2592000